/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: Wesai (https://sketchfab.com/Wesai)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokemon-rse-pokemon-center-ae2858d8d212406ebe95927d4f17d328
Title: Pokemon RSE - Pokemon Center
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.17}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Wall_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.Floor_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.Balcony_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.Pokeball_01_RSE_pokeball_0.geometry}
            material={materials.RSE_pokeball}
          />
          <mesh
            geometry={nodes.Pokeball_02_RSE_pokeball_0.geometry}
            material={materials.RSE_pokeball}
          />
          <mesh
            geometry={nodes.Bookshelf_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.HealingMachine_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.M_Pokeball_01_RSE_pokeball_0.geometry}
            material={materials.RSE_pokeball}
          />
          <mesh
            geometry={nodes.M_Pokeball_02_RSE_pokeball_0.geometry}
            material={materials.RSE_pokeball}
          />
          <mesh
            geometry={nodes.M_Pokeball_03_RSE_pokeball_0.geometry}
            material={materials.RSE_pokeball}
          />
          <mesh
            geometry={nodes.M_Pokeball_04_RSE_pokeball_0.geometry}
            material={materials.RSE_pokeball}
          />
          <mesh
            geometry={nodes.M_Pokeball_05_RSE_pokeball_0.geometry}
            material={materials.RSE_pokeball}
          />
          <mesh
            geometry={nodes.M_Pokeball_06_RSE_pokeball_0.geometry}
            material={materials.RSE_pokeball}
          />
          <mesh
            geometry={nodes.TV_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.PC_01_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.PC_02_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.Tree_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.Table_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.Chair_01_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.Chair_02_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.Chair_03_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.Chair_04_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.Chair_05_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.Chair_06_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.Escalator_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.TY_Chansey_RSE_misc_0.geometry}
            material={materials.RSE_misc}
          />
          <mesh
            geometry={nodes.Carpet_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.Map_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
          <mesh
            geometry={nodes.Occlusion_RSE_mat_0.geometry}
            material={materials.RSE_mat}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
